version: "3"
services: 
    app:
      container_name: RestApi
      restart: always
      build: .
      ports:
        - '7878:7878'
      links:
        - mysql
    mongo:
      container_name: mysql
      image: mysql
      ports: 
        - '3306:3306'